require("options")
require("mappings")
require("plugins")
require("colorscheme")

require("plugins.autopairs")
require("plugins.barbar")
require("plugins.compe")
require("plugins.fugitive")
require("plugins.galaxyline")
require("plugins.gitsigns")
require("plugins.nvimtree")
require("plugins.telescope")
require("plugins.tmuxnavigator")
require("plugins.treesitter")
require("plugins.colorizer")
require("plugins.indentblankline")
require("plugins.relativenum")

require("lsp")
require("lsp.tsserver")
require("lsp.pyright")
require("lsp.rust_analyzer")
require("lsp.cssls")
require("lsp.html")
