require("options")
require("mappings")
require("colorscheme")

require("plugins")
require("plugins/telescope")
require("plugins/fugitive")
require("plugins/tmuxnavigator")
require("plugins/compe")
require("plugins/treesitter")
require("plugins/galaxyline")
require("plugins/autopairs")
require("plugins/barbar")
require("plugins/gitsigns")
require("plugins/tree")

require("plugins/lsp")
require("plugins/lsp/tsserver")
