require("options")
require("mappings")
require("plugins")
require("colorscheme")

require("plugins/autopairs")
require("plugins/barbar")
require("plugins/compe")
require("plugins/fugitive")
require("plugins/galaxyline")
require("plugins/gitsigns")
require("plugins/nvimtree")
require("plugins/telescope")
require("plugins/tmuxnavigator")
require("plugins/treesitter")
require("plugins/colorizer")

require("lsp")
require("lsp/tsserver")
