#!/bin/sh

# This scripts produces ctags available at .git/tags location.
# Tags will be ignored by git, although used by vim because of fugitive plugin.
# Generated in background, so no distraction and sync waiting.
# Kudos to tpope - https://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
		ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql
		mv "$dir/$$.tags" "$dir/tags"
